/* eslint-disable react/function-component-definition */
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { Button } from '@mui/material';
import Grid from '@mui/material/Grid';
import styles from '../styles/Home.module.css';
import ResturantStatusButton from '../components/ResturantStatusButton';
import OrderTab from '../components/OrderTab';

const Home: NextPage = () => (
  <div className={styles.container}>
    <Head>
      <title>Project Mercury</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main>
      <Grid container direction="row" alignItems="center">
        <Grid item xs={8}>
          <h1 className={styles.title}>Order Manager</h1>
        </Grid>
        <Grid item xs={2}>
          <Button variant="outlined">Item availability</Button>
        </Grid>
        <Grid item xs={0}>
          <ResturantStatusButton />
        </Grid>
      </Grid>
      <OrderTab />
    </main>

    <footer className={styles.footer}>
      <a
        href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
        target="_blank"
        rel="noopener noreferrer"
      >
        Powered by{' '}
        <span className={styles.logo}>
          <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </span>
      </a>
    </footer>
  </div>
);

export default Home;
